version: "3"

volumes:
  mysql-data:

services:
  database:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: ${DB_NAME:-goesic}
      MYSQL_USER: ${DB_USER:-goesic}
      MYSQL_PASSWORD: ${DB_PASSWORD:-goesic}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-goesic}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./goesic.sql:/docker-entrypoint-initdb.d/goesic.sql
    ports:
      - ${FORWARD_MYSQL_PORT:-0}:3306
  