version: "3"

volumes:
  mysql-data:

services:
  app:
    build:
      context: .
    restart: unless-stopped
    command: 
      - bash
      - -c
      - "go get && gow -e=go,env,html run main.go"
    logging:
      options:  
        max-size: "500k"
        max-file: "2"
    volumes:
      - ./:/go/src/app
    ports:
      - ${FORWARD_APP_PORT:-8080}:8080
  database:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: ${DB_NAME:-goesic}
      MYSQL_USER: ${DB_USER:-goesic}
      MYSQL_PASSWORD: ${DB_PASSWORD:-goesic}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-goesic}
    logging:
      options:  
        max-size: "500k"
        max-file: "2"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./goesic.sql:/docker-entrypoint-initdb.d/goesic.sql
    ports:
      - ${FORWARD_MYSQL_PORT:-0}:3306
  